name: Check index status and send emails
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1.1.1
      with:
        args: -H "Authorization:${{ secrets.AUTHORIZATION_CODE }}" https://searchmynotion.com/api/github
